jobs:
  release:
    if: '!contains(github.event.head_commit.message, ''skip ci'')'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out repository
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Install Java and Maven
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: '11'
    - continue-on-error: true
      name: Adding ssh key
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.ssh_private_key }}
    - continue-on-error: true
      name: Git configuration
      run: 'git config user.email "ci@wmixvideo.com.br"

        git config user.name "Wmix CI"

        '
    - continue-on-error: true
      name: Release Maven package
      uses: samuelmeuli/action-maven-publish@v1.4.0
      with:
        gpg_passphrase: ${{ secrets.gpg_passphrase }}
        gpg_private_key: ${{ secrets.gpg_private_key }}
        maven_goals_phases: clean -B release:prepare release:perform -Darguments="-DskipTests"
          -P central
        nexus_password: ${{ secrets.nexus_password }}
        nexus_username: ${{ secrets.nexus_username }}
    - continue-on-error: true
      name: Set up Java for publishing to GitHub Packages
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: '11'
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Publish to GitHub Packages
      run: mvn --batch-mode deploy -P github
name: Release Master
on:
  repository_dispatch:
    types: trigger-ga___release.yml
